# Topic heading

When a Mule app starts, a //passive voice - does the app run the connectivity test?// connectivity test runs on components, such as the HTTP or FTP connector //what are the components exactly, and what is a HTTP connector, for one?//, that need to connect to an external server //more details about the external server// //new sentence// If the test fails, the default behavior logs a warning message and continues with the deployment //first time mentioning of deployment - what specific does deployment refer to? the connectivity test and the success?// of the app, instead of blocking //what specifically is blocking refer to here? a test fail? //the deployment.

You can modify this behavior //the behavior is the connection testing? deployment? the deployment process (still need to know what deployment refers to)// by setting a number of reconnection attempts // what are the options to modify the "behavior"// to try after an initial failure and by forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconection (reconnect) attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them.   
  
  The default setting is 2 reconnection attempts at a frequency of `2000ms' For example, you might change the default settings to a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms):  
  
  
  <http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
 

[source,xml]


* Reconnect Forever (reconnect-forever): Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Defaults to every 2000 ms. Because there is no limit on the number of retries, no value for count is specified.

* Example that does not set a limit on the number of reconnection attempts:

* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
