When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector, that need to connect to an external server. If the test fails, the system logs a warning message and continues with the deployment of the app, instead of blocking the deployment.

== Customizing the Reconnection Behavior

You can modify this behavior by setting a number of reconnection attempts to try after an initial failure and by forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): +
Forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): +
Limits the number of reconnection attempts and the interval at which to execute them. 
* Reconnect Forever (`reconnect-forever`): +
Does not limit the number of reconnection attempts.

== Examples

**Example of limiting reconnection attempts**

This example shows a code snippet that tells the deployment to fail after five reconnection attempts are exhausted. It sets a count of five reconnection attempts at a frequency of every 4000 milliseconds (ms). It defaults to two reconnection attempts at a frequency of 2000ms.

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

**Example of not setting a limit on the number of reconnection attempts**

The following example uses the `reconnect-forever` parameter tells the deployment to reconnect at every 4000 ms for as long as the app runs. The default is to attempt to reconnect every 2000 ms. Because there is no limit on the number of retries, no value for count is specified.

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connectio>
----





