When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP Connector, that must connect to an external server. If the test fails, Mule's default behavior is to log a warning message and continue deploying the app, instead of blocking the deployment.

You can modify this behavior by setting a number of reconnection attempts for Mule to try after an initial failure and by forcing the deployment to fail when all connection attempts fail.

* Fails Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and specifies the interval at which they are executed. For example, you might set a `count` of five reconnection attempts at a `frequency` of every `4000ms`. The default setting of `reconnect` is two reconnection attempts at a `frequency` of `2000ms`.
* The following example specifies that a deployment should fail after five failed reconnection attempts at a frequency of 4000ms:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/>
    </reconnection>
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a specified interval, for example every 4000ms, for as long as the app runs. The default setting of `reconnect-forever` is two reconnection attempts every 2000ms. Because there is no limit on the number of attempts, no value for `count` is specified.

* The following example specifies that the app should attempt to connect at a frequency of 4000ms with no limit on the number of attempts:
+
[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
  <reconnection>
    <reconnect-forever frequency="4000" count=""/>
  </reconnection>
</http:request-connection>
----
