When a Mule app starts, a connectivity test runs on components, such as HTTP or FTP connectors, that need to connect to an external server. If the test fails, by default, the Mule app logs a warning message, and the deployment of the app continues.

You can modify the default behavior by setting the number of times that the component attempts to connect to an external serer after the initial test fails. You can also configure the deployment to fail when all the attempts at reconnecting the component to the external server fails.

You can use the following settings to modify the default behavior:

* Fail Deployment (`failsDeployment`): Forces the deployment to fail after the number of reconnection attempts between the component and external server fail.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and specifies the interval at which to run each reconnection attempt. For example, you can specify that the compponent attempts to reconnect to the server after 5 attempts at a `frequency` of every `4000` milliseconds (ms). By default, the number of reconnection attempts is 2 with a frequency of `2000ms`.
* In the following example, the connection fails after 5 reconnection attempts fail at a frequency of 4000 milliseconds:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (reconnect-forever): Attempts to reconnect the component to the external server at a given interval, for example, every 4000 ms, during the time that the app runs. The default value is 2000 ms. If you do not want to set a limit on the number of reconnection attempts, you do not need to set a value for it.

* The following example shows 5 reconnection attempts at a frequency of 4000 ms:

* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
