When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector, that need to connect to an external server. If the test fails, the default behavior is to log a warning message. Instead of blocking the deployment, the test continues with the deployment of the app.

You can modify this behavior by setting a number of reconnection attempts that kick off after an initial failure. When all connection attempts fail, then the deployment fails. 

* `failsDeployment`: Forces the deployment to fail if the connection fails and reconnection attempts are exhausted.
* `reconnect`: Limits the number of reconnection attempts and the interval at which to execute them. Defaults to 2 reconnection attempts at a frequency of 2000 ms. 
* `reconnect-forever`: Attempts to reconnect at a given interval as long as the app runs. Defaults to every 2000 ms. Because there is no limit on the number of reconnection attempts, no value for count is specified. 

// Why should someone increase or decrease the frequency or count? Are there things that they should take into account like their bandwidth?

The following example shows a deployment failure after 5 reconnection attempts. Each reconnection attempt occurs after 4000 ms:

// Do we need to tell them that they have to use port 80 and why? Can they use other ports?

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----

The following example does not set a limit on the number of reconnection attempts. Each reconnection attempt occurs after 4000 ms:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" >
  </reconnection>
</http:request-connection>
----
