= Configure the starting behavior of Mule apps

You can configure the starting behavior of Mule apps. When a Mule app starts, a connectivity test runs on components that need to connect to an external server, such as the HTTP or FTP connector. By default, if the test fails a warning message is logged and the app deployment continues. You can configure apps to attempt to reconnect to components a specified number of times and stop deployment if the app cannot successfully connect.

In the app configuration file, adjust any of the following options:

* **Fail Deployment (`failsDeployment`)** +
 Forces the deployment to fail if the connection isn't successful. Valid values are True or False.
* Reconnect (`reconnect`) +
 Limits the number of reconnection attempts and the interval at which to execute them. For example, you can specify to perform five reconnection attempts, one every 4000 miliiseconds (ms). 
 +
 [NOTE]
 The default behavior is to try to connect twice at a frequency of 2000 ms.
 +
 The example configuration below allows an app to try to connect five times at a frequency of 4000 ms:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----
+
* **Reconnect Forever (reconnect-forever)** 
Attempts to reconnect at a specified interval. For example, you can configure an app to attempt to connect every 4000 ms indefinitely. The default interval is 2000 ms.
+
[NOTE]
There is no limit on the number of times an app can attempt to connect, so no count value is included by default.
+

The example configuration below doesn't set a limit on the number of reconnection attempts:
+
* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
